# Generated by Django 4.2.1 on 2023-06-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Category_Image')),
                ('product_name', models.CharField(max_length=25)),
                ('product_category', models.CharField(max_length=25)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AddCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('billing_address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('zip_code', models.PositiveIntegerField()),
                ('customer_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AddPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=25)),
                ('product_category', models.CharField(max_length=30)),
                ('brand_name', models.CharField(max_length=30)),
                ('supplier_name', models.CharField(max_length=30)),
                ('product_color', models.CharField(max_length=20)),
                ('product_size', models.CharField(max_length=10)),
                ('product_quantity', models.PositiveIntegerField()),
                ('order_tax', models.CharField(max_length=12)),
                ('order_discount', models.PositiveIntegerField()),
                ('shipping_charge', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('purchase_status', models.CharField(max_length=20)),
                ('payment_status', models.CharField(max_length=20)),
                ('product_image', models.ImageField(upload_to='Purchase_Image')),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AddReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=25)),
                ('product_category', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_phone', models.CharField(max_length=30)),
                ('customer_email', models.EmailField(max_length=254)),
                ('return_quantity', models.PositiveIntegerField()),
                ('return_price', models.PositiveIntegerField()),
                ('payment_status', models.CharField(max_length=20)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AddSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_name', models.CharField(max_length=30)),
                ('product_category', models.CharField(max_length=30)),
                ('order_id', models.IntegerField()),
                ('brand_name', models.CharField(max_length=40)),
                ('supplier_name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=15)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('product_color', models.CharField(max_length=12)),
                ('product_size', models.CharField(max_length=10)),
                ('stock_quantity', models.IntegerField()),
                ('order_quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('order_tax', models.IntegerField()),
                ('order_discount', models.IntegerField()),
                ('shipping_charge', models.IntegerField()),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
                ('product_image', models.ImageField(upload_to='Product_Image')),
                ('total_amount', models.IntegerField()),
                ('sale_status', models.CharField(max_length=20)),
                ('payment_status', models.CharField(max_length=20)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AddSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('contact_person_name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('zip_code', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
