# Generated by Django 4.2.1 on 2023-06-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSDBAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpurchase',
            name='order_discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addpurchase',
            name='order_tax',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addpurchase',
            name='product_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addpurchase',
            name='shipping_charge',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addpurchase',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addpurchase',
            name='unit_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addsale',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='Product_Image'),
        ),
    ]
