# Generated by Django 4.2.1 on 2023-07-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSDBAPP', '0007_alter_addsale_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsale',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
